// <auto-generated />
using System;
using Inmobiliaria_Benito.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inmobiliaria_Benito.Migrations
{
    [DbContext(typeof(InmobBenitoContext))]
    partial class InmobBenitoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Contrato", b =>
                {
                    b.Property<int>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContratoId"));

                    b.Property<DateOnly?>("FechaDesde")
                        .HasColumnType("date")
                        .HasColumnName("fecha_desde");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_hasta");

                    b.Property<int?>("IdInmueble")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_inmueble");

                    b.Property<int?>("IdInquilino")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_inquilino");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.HasKey("ContratoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdInmueble" }, "id_inmueble");

                    b.HasIndex(new[] { "IdInquilino" }, "id_inquilino");

                    b.ToTable("contrato", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Inmueble", b =>
                {
                    b.Property<int>("InmuebleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InmuebleId"));

                    b.Property<int?>("Ambientes")
                        .HasColumnType("int(11)")
                        .HasColumnName("ambientes");

                    b.Property<string>("Coordenadas")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("coordenadas");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion");

                    b.Property<int?>("IdPropietario")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_propietario");

                    b.Property<int?>("IdTipo")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_tipo");

                    b.Property<decimal?>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.Property<string>("Uso")
                        .HasColumnType("enum('comercial','residencial')")
                        .HasColumnName("uso");

                    b.HasKey("InmuebleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPropietario" }, "id_propietario");

                    b.HasIndex(new[] { "IdTipo" }, "id_tipo");

                    b.ToTable("inmueble", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Inquilino", b =>
                {
                    b.Property<int>("InquilinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InquilinoId"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("InquilinoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Dni" }, "dni")
                        .IsUnique();

                    b.ToTable("inquilino", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<int?>("ContratoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_contrato");

                    b.Property<DateOnly?>("FechaPago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal?>("Importe")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("importe");

                    b.Property<int?>("NumeroPago")
                        .HasColumnType("int(11)")
                        .HasColumnName("numero_pago");

                    b.HasKey("PagoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ContratoId" }, "id_contrato");

                    b.ToTable("pago", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Propietario", b =>
                {
                    b.Property<int>("PropietarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PropietarioId"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("PropietarioId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Dni" }, "dni")
                        .IsUnique()
                        .HasDatabaseName("dni1");

                    b.ToTable("propietario", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.TipoInmueble", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("TipoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique();

                    b.ToTable("tipo_inmueble", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .HasColumnType("enum('administrador','empleado')")
                        .HasColumnName("rol");

                    b.HasKey("UsuarioId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Contrato", b =>
                {
                    b.HasOne("Inmobiliaria_Benito.Models.Inmueble", "IdInmuebleNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("IdInmueble")
                        .HasConstraintName("contrato_ibfk_2");

                    b.HasOne("Inmobiliaria_Benito.Models.Inquilino", "IdInquilinoNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("IdInquilino")
                        .HasConstraintName("contrato_ibfk_1");

                    b.Navigation("IdInmuebleNavigation");

                    b.Navigation("IdInquilinoNavigation");
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Inmueble", b =>
                {
                    b.HasOne("Inmobiliaria_Benito.Models.Propietario", "IdPropietarioNavigation")
                        .WithMany("Inmuebles")
                        .HasForeignKey("IdPropietario")
                        .HasConstraintName("inmueble_ibfk_1");

                    b.HasOne("Inmobiliaria_Benito.Models.TipoInmueble", "IdTipoNavigation")
                        .WithMany("Inmuebles")
                        .HasForeignKey("IdTipo")
                        .HasConstraintName("inmueble_ibfk_2");

                    b.Navigation("IdPropietarioNavigation");

                    b.Navigation("IdTipoNavigation");
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Pago", b =>
                {
                    b.HasOne("Inmobiliaria_Benito.Models.Contrato", "IdContratoNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("ContratoId")
                        .HasConstraintName("pago_ibfk_1");

                    b.Navigation("IdContratoNavigation");
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Contrato", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Inmueble", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Inquilino", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.Propietario", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("Inmobiliaria_Benito.Models.TipoInmueble", b =>
                {
                    b.Navigation("Inmuebles");
                });
#pragma warning restore 612, 618
        }
    }
}
